import os

UP = r'C:\Users\USER\Documents\rbxsluauedicationalcripts\Universery\Libraries\Aimwork\upstream\src'
VENDOR = r'C:\Users\USER\Documents\rbxsluauedicationalcripts\Universery\Libraries\Aimwork\vendor\trove\init.luau'
OUT = r'C:\Users\USER\Documents\rbxsluauedicationalcripts\Universery\src\gen\aimwork_blobs.luau'

# module key -> source path
MODULES = {
    'aimwork': 'src/init.luau',
    'core/config': 'src/core/config.luau',
    'functions/getCharacter': 'src/functions/getCharacter.luau',
    'functions/getCurrentCamera': 'src/functions/getCurrentCamera.luau',
    'functions/isPointInsideRect': 'src/functions/isPointInsideRect.luau',
    'functions/mergeTables': 'src/functions/mergeTables.luau',
    'functions/init': 'src/functions/init.luau',
    'modules/PlayerTracker': 'src/modules/PlayerTracker/init.luau',
    'modules/PlayerTracker/PlayerObject': 'src/modules/PlayerTracker/PlayerObject.luau',
    'modules/VisualHandler': 'src/modules/VisualHandler/init.luau',
    'modules/VisualHandler/FovObject': 'src/modules/VisualHandler/FovObject.luau',
    'modules/checks': 'src/modules/checks.luau',
    'patches': 'src/patches/init.luau',
    'patches/example': 'src/patches/example.luau',
    'types/aimwork': 'src/types/aimwork.luau',
    'types/extra_drawing': 'src/types/extra_drawing.luau',
    'types/fov_object_like': 'src/types/fov_object_like.luau',
    'types/selected': 'src/types/selected.luau',
    'pkgs/trove': VENDOR,
}

BASE = r'C:\Users\USER\Documents\rbxsluauedicationalcripts\Universery\Libraries\Aimwork\upstream'


def read_src(rel):
    if rel is None:
        return None
    if os.path.isabs(rel):
        p = rel
    else:
        p = os.path.join(BASE, *rel.split('/'))
    with open(p, 'rb') as f:
        return f.read().decode('utf-8')


def check(src, key):
    assert ']===]' not in src, 'bracket collision in ' + key
    assert '\r' not in src, 'CR found in ' + key


parts = []
parts.append('-- GENERATED by tools/gen_blobs.py from upstream/ + vendor/. Do not edit.')
parts.append('-- Regenerate after any upstream/vendor change, then rebuild dist.')
parts.append('Universery.AimworkSources = {')
for key in sorted(MODULES):
    if key == 'modules/PlayerTracker/init_alias':
        continue
    src = read_src(MODULES[key])
    check(src, key)
    parts.append('\t["' + key + '"] = [===[')
    parts.append(src.rstrip('\n'))
    parts.append(']===],')
parts.append('}')
os.makedirs(os.path.dirname(OUT), exist_ok=True)
blob = '\n'.join(parts) + '\n'
open(OUT, 'w', encoding='utf-8', newline='').write(blob)
print('wrote', OUT, len(blob), 'bytes')
